#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys
os.chdir(os.path.split(os.path.realpath(sys.argv[0]))[0])
import wx

from consts import *
from ui.mainwin import *

class MyApp(wx.App):

    def OnInit(self):
	self.mainframe = MyFrame(None)
	self.mainframe.Show()
	self.SetTopWindow(self.mainframe)
	return True
	
    def MacReopenApp(self):
        """Called when the doc icon is clicked, and ???"""
        self.GetTopWindow().Raise()

if __name__ == '__main__':
    app = MyApp(filename=LOG_FILE)
    app.MainLoop()
