#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys
os.chdir(os.path.split(os.path.realpath(sys.argv[0]))[0])
import wx

from consts import *
from MyFrame import *
from DlgLogin import *

L = wx.Locale()

class MyApp(wx.App):

    def OnInit(self):
    	L.Init(wx.LANGUAGE_DEFAULT)
        L.AddCatalogLookupPathPrefix(r'locale')
        L.AddCatalog('messages')
	self.mainframe = MyFrame()
	self.mainframe.frame.Show()
	self.SetTopWindow(self.mainframe.frame)
	return True


if __name__ == '__main__':
    app = MyApp(False)
    app.MainLoop()
