#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys
os.chdir(os.path.abspath(os.path.dirname(sys.argv[0])))
import wx

from consts import *
from MyFrame import *
from DlgLogin import *

class MyApp(wx.App):

    def OnInit(self):
	self.mainframe = MyFrame()
	self.mainframe.frame.Show()
	self.SetTopWindow(self.mainframe.frame)
	cfg1 = wx.FileConfig(APPCODENAME)
	if cfg1.Read('/Login/UserID') and cfg1.Read('/Login/AutoLogin'):
		pass
	else:
		DlgLogin().dialog.ShowModal()
		if self.mainframe.get_user_id():
			self.mainframe.frame.SetTitle('%s [%s: %s]' % (APPNAME, 'User', self.mainframe.get_user_id()))
		else:
			self.mainframe.frame.SetTitle(APPNAME)
	return True


if __name__ == '__main__':
    app = MyApp(False)
    app.MainLoop()
